// for objects common to validation purposes: task payload conversion and form values validation
import { format, parse } from 'date-fns';

// these formats are generated by default date and time picker from bootstrap/normal form-control
export const DATE_PICKER_FORMAT = "yyyy-MM-dd"; //e.g 2022-01-05
export const TIME_PICKER_FORMAT = "HH:mm" // e.g 21:06
const DEFAULT_TIME = "00:00"

// parse(inputStr, formatStr, referenceDate to fill in missing parts)
// assume both non-empty: this is for case date, time both provided
export const dateTimeInputsToDate =(date: string, time: string): Date => {
    const sep = "";
    return parse(`${date + sep + time}`,
     `${DATE_PICKER_FORMAT + sep + TIME_PICKER_FORMAT}`,
      new Date()
    )
};

// input: dateStr following DATE_PICKER_FORMAT
// output: Date object with that date and time set to 12am (stand in for "default time")
export const generate12AMDateFromDateStr = (dateStr:string):Date => {
   return dateTimeInputsToDate(dateStr, DEFAULT_TIME);
}

// input: date ISO string 
// output: dateStr according to DATE_PICKER_FORMAT
export const dateISOToDateStr = (dateISO:string):string => {
    return format(new Date(dateISO), DATE_PICKER_FORMAT);
}

// input: dateISO string
// output: timeStr according to TIME_PICKER_FORMAT
export const dateISOToTimeStr = (dateISO:string):string => {
  return format(new Date(dateISO), TIME_PICKER_FORMAT);
}

